name: gsettings
version: 0.2.8
publish_to: none
description:
  Provides a client to access GSettings - a settings database used for storing user preferences on Linux.

homepage: https://github.com/canonical/gsettings.dart

environment:
  sdk: '>=3.12.0 <4.0.0'

platforms:
  linux:

dependencies:
  dbus: 
    git: https://github.com/kumsumit/dbus.dart.git
  xdg_directories: ^1.1.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
  test_cov: ^1.0.1
